name: 'Various checks for the repository'

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

jobs:
  secret-detection:
    uses: Yellow-Dog-Man/composite-actions-templates/.github/workflows/secret-detection.yml@main
    permissions:
      contents: read
